variables:
  COMPOSER_CACHE_DIR: ".cache/composer"
  DOCROOT: "${CI_PROJECT_DIR}"

stages:
  - build
  - test

test:
  stage: test
  tags: [docker]
  image: registry.gitlab.com/dmore/docker-chrome-headless
  script:
    - rm -f composer.lock
    - composer install -o --ansi --no-progress
    - vendor/bin/phpunit --colors=always
  cache:
    key: common
    paths:
      - .cache
      - vendor
